### ISSUE TITLE
Could not find method google() for arguments [] on repository container.

### ISSUE THREAD

**Issue by dsuprano** [BlackBoxVision/react-native-mercadopago-checkout#11]
I have this error when run on android:

![image](https://user-images.githubusercontent.com/31738926/33128203-514713cc-cf6a-11e7-80a8-2cedbae66119.png)

Any idea? Thx.

#7

**Comment by dsuprano** [comment]
@JonatanSalas por favor, si querés escribime para apoyarte en el desarrollo, hice unas modificaciones que hicieron "funcionar" en android.

**Comment by JonatanSalas** [comment]
@dsuprano si tenes alguna forma de mejorarlo, siempre es bienvenido un PR!

**Comment by goncalveslucasv** [comment]
@dsuprano Como lo pudiste solucionar?? me aparece el mismo error =(



```
* Where:
Build file '/var/www/project-redux/node_modules/react-native-mercadopago-checkout/android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating project ':react-native-mercadopago-checkout'.
> Could not find method google() for arguments [] on repository container.

```

**Comment by dsuprano** [comment]
@goncalveslucasv en tu package.json coloca "react-native-mercadopago-checkout": "https://github.com/dsuprano/react-native-mercadopago-checkout.git#master" a ver si te funciona, es un fork que hice para eliminar ese error.

**Comment by goncalveslucasv** [comment]
@dsuprano Genial ! funciono perfecto :D muchas gracias! pudiste pasarlo a español??

**Comment by dsuprano** [comment]
@goncalveslucasv Disculpa no entendí, a que te refieres con pasarlo a español? Saludos.

**Comment by goncalveslucasv** [comment]
@dsuprano El UI lo tengo default en ingles, es decir cuando ejecuto el sdk aparece "How do you want to pay?" En vez de "Como quieres pagar?"

**Comment by dsuprano** [comment]
@goncalveslucasv Tengo entendido que el SDK hace lectura del lenguaje del dispositivo, capaz tienes tu teléfono o emulador en ingles, si no es eso, no tengo idea por el momento que otra cosa podría ser.

**Comment by githubmss** [comment]
Getting same issue

**Comment by JonatanSalas** [comment]
I'm closing this issue, because we're deprecating this library in favor of adding a newer one which fixes the vast majority of the bugs.
