### ISSUE TITLE
class rctcxxmodule was not exported. did you forget to use rct_export_module() ?

### ISSUE THREAD

**Issue by MssMaster** [BlackBoxVision/react-native-mercadopago-checkout#12]
I got this error when add manually mercado sdk . But got error undefined Object (MercadoPagoCheckoutModule.startForPayment()) method.
Please help me to solve this problem in ios and its working in android fine.
Thanks in advance.

**Comment by JonatanSalas** [comment]
I'm closing this issue, because we're deprecating this library in favor of adding a newer one which fixes the vast majority of the bugs.
