### ISSUE TITLE
MercadoPagoSDK module not found in ios

### ISSUE THREAD

**Issue by MssMaster** [BlackBoxVision/react-native-mercadopago-checkout#13]
In ios  give me error "MercadoPagoSDK module not found in ios" in appDelegate.m file of library checkout_mercado_module.
In android its working fine . 
And i need it to implement in ios on periority. Please tell me the solution.

**Comment by JonatanSalas** [comment]
I'm closing this issue, because we're deprecating this library in favor of adding a newer one which fixes the vast majority of the bugs.
