### ISSUE TITLE
Dependency problem 'com.android.support:support-v4' 

### ISSUE THREAD

**Issue by glevymayo** [BlackBoxVision/react-native-mercadopago-checkout#14]
I get the following error when installing the component:
Android dependency 'com.android.support:support-v4' has different version for the compile (27.0.2) and runtime (27.1.1) classpath. You should manually set the same version via DependencyResolution
How do I solve it? Do you need more details? Which ones?

**Comment by JonatanSalas** [comment]
I'm closing this issue, because we're deprecating this library in favor of adding a newer one which fixes the vast majority of the bugs.
