### ISSUE TITLE
[Documentation] - Android Setup

### ISSUE THREAD

**Issue by jzelayeta** [BlackBoxVision/react-native-mercadopago-checkout#7]
Could you please add setup documentation for Android?

**Comment by JonatanSalas** [comment]
@jzelayeta For sure! Tomorrow I will do it!

**Comment by jzelayeta** [comment]
Sorry for insist again with this, but have you finished the doc for Android setup?

Thx

**Comment by goncalveslucasv** [comment]
Hello, I am interested in incorporating MercadoPago into my project. I would greatly appreciate the documentation for android

thx!

**Comment by leandroahmad** [comment]
Hello! I also need help with the Android Setup.

Thanks!

**Comment by JonatanSalas** [comment]
I'm closing this issue, because we're deprecating this library in favor of adding a newer one which fixes the vast majority of the bugs.
