### ISSUE TITLE
"react-native-checkout-mercadopago" or "react-native-mercadopago-checkout" ??

### ISSUE THREAD

**Issue by goncalveslucasv** [BlackBoxVision/react-native-mercadopago-checkout#9]
Hi, I'm having problems executing the sample project.
When I try to execute the example it shows me the following error:

````
/var/www/mp-eatq/node_modules/react-native-mercadopago-checkout/android/src/main/java/com/blackboxvision/reactnative/mercadopagocheckout/MercadoPagoCheckoutEventListener.java:19: error: MercadoPagoCheckoutEventListener is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public final class MercadoPagoCheckoutEventListener implements ActivityEventListener {
             ^
/var/www/mp-eatq/node_modules/react-native-mercadopago-checkout/android/src/main/java/com/blackboxvision/reactnative/mercadopagocheckout/MercadoPagoCheckoutEventListener.java:82: error: method does not override or implement a method from a supertype
    @Override
    ^
2 errors
:react-native-mercadopago-checkout:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

`

**Comment by JonatanSalas** [comment]
@goncalveslucasv There's a trouble that I have to fix related to react-native version, and java android interfaces. It seems that with latest releases of react-native, ActivityEventListener interface has changed some methods, and also deprecated other ones.

**Comment by JonatanSalas** [comment]
@goncalveslucasv Today I will try to review it. I will do it by the night. Now I'm at work!

**Comment by goncalveslucasv** [comment]
thank you very much jonatan!!

if you have a package.json of old versions of the dependencies would help me to test!

**Comment by goncalveslucasv** [comment]
@JonatanSalas Hi ! how are you? Could you see this error? I'm stuck in the payment process :(

**Comment by JonatanSalas** [comment]
@goncalveslucasv I have sent you a private message through the meetup JS slack.

**Comment by Andresagustin** [comment]
Hey any luck with this?

**Comment by juampi92** [comment]
Any updates?

**Comment by JonatanSalas** [comment]
I'm closing this issue, because we're deprecating this library in favor of adding a newer one which fixes the vast majority of the bugs.
